### ISSUE TITLE
页面统计相关

### ISSUE THREAD

**Issue by IsMrWu** [ccj659/JJV#5]
是出于什么考虑没有加入页面统计？

**Comment by ccj659** [comment]
页面统计pageview 有得啊~ JJEvent.screen()方法就是.

**Comment by nicelyjust** [comment]
@ccj659 screen方法 LTPType添加需要的类型吗?
    SCREEN_LTP_REFRESH(1),//下拉刷新
    SCREEN_LTP_NEXT_PAGE(2), //翻页
    SCREEN_LTP_NEXT_TAB(3),//标签切换
    SCREEN_LTP_POP_WINDOW(4), //局部弹出
    SCREEN_LTP_FILTER_REFRESH(5);//筛选刷新
感谢分享

**Comment by ccj659** [comment]
这个刚开始的设计用意，就是不同的 屏幕值类型。默认添加SCREEN_LTP_REFRESH就行
